package com.market.pipeline.ingestor;

import com.market.pipeline.common.avro.Tick;
import io.confluent.kafka.serializers.KafkaAvroDeserializer;
import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.util.Collections;
import java.util.Properties;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

/**
 * Integration tests for the Market Data Ingestor service.
 * Verifies that the ingestor correctly generates mock market data and publishes it to Kafka.
 */
public class IngestorIntegrationTest extends AbstractIngestorIntegrationTest {

    /**
     * Verifies that market ticks are correctly produced to the "market.data.raw" topic.
     */
    @Test
    void shouldGenerateAndProduceMarketData() {
        // Prepare consumer for "market.data.raw" topic
        Properties props = new Properties();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, kafka.getBootstrapServers());
        props.put(ConsumerConfig.GROUP_ID_CONFIG, "test-ingestor-group");
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, KafkaAvroDeserializer.class.getName());
        props.put("schema.registry.url", "http://" + schemaRegistry.getHost() + ":" + schemaRegistry.getMappedPort(8081));
        props.put("specific.avro.reader", "true");

        try (Consumer<String, Tick> consumer = new KafkaConsumer<>(props)) {
            consumer.subscribe(Collections.singletonList("market.data.raw"));

            // Wait for at least one tick to be generated by the scheduled task
            await().atMost(Duration.ofSeconds(10)).untilAsserted(() -> {
                ConsumerRecords<String, Tick> records = consumer.poll(Duration.ofMillis(500));
                assertThat(records).isNotEmpty();
                Tick tick = records.iterator().next().value();
                assertThat(tick.getSymbol()).isIn("AAPL", "GOOGL", "MSFT", "AMZN", "TSLA");
            });
        }
    }
}
